version: "3"

services:
  postgres:
    image: postgres:14.8-alpine
    container_name: postgres_container
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
